### ISSUE TITLE
Fix hardcoding of "/bag/" in makeObjectFeed

### ISSUE THREAD

**Issue by ldko** [unt-libraries/codalib#18]
In `bagatom.makeObjectFeed` we are [hardcoding `"/bag/"`](https://github.com/unt-libraries/codalib/blob/master/codalib/bagatom.py#L381) into the entries' alternate links,

`updated=dateStamp,  alt=webRoot+"/bag/"+getattr(o, idAttr),`

`makeObjectFeed` is used for more than just bag feeds though, so it is causing incorrect links in other feeds. For instance, this can be seen as a problem in the Premis Event Service at `/APP/event/` where entries are ending up with "bag" in the links.

**Comment by runderwood** [comment]
What if we add an entry alt uri template kwarg? Maybe even allow a callable there?

Otherwise, I have to assume all collections are named the same and follow the same rules..

**Comment by runderwood** [comment]
Like [this](https://github.com/unt-libraries/codalib/commit/23cbd2f3e4397b8f5eaf0e220024b0b5ed11f4a2)?

**Comment by ldko** [comment]
that should work
