### ISSUE TITLE
updateObjectFromXML allows may assign incorrect element text

### ISSUE THREAD

**Issue by ldko** [unt-libraries/codalib#21]
The way [`updateObjectFromXML`](https://github.com/unt-libraries/codalib/blob/master/codalib/bagatom.py#L442) is written, it allows for incorrect text to be assigned to an element if an element's tag contains the string of another element tag. For example, a PREMIS event entry modified with a PUT request will end up with the text for  `eventOutcome` in the `eventOutcomeDetailNote` element.

**Comment by runderwood** [comment]
Maybe I'm missing something, but having functions like `updateObjectFromXML` in `codalib` doesn't seem all that useful. Passing a callable to the library only for it to call it on an XML tree *the caller already had* doesn't make sense, again, unless I'm missing something.

To me, it seems like, ideally, (de)serialization should live in models. Would it make more sense to provide a class for mixins that does basic XML (de)serialization and use that for mapping between objects and XML representations? Something like:

    my_model_instance = MyModel.from_xml(xml_str)
    my_model_el = my_model_instance.to_element()
    my_atom_entry = codalib.wrap_entry(my_model_el, author='State College Library'...)

But this is biting off a bit more than is absolutely necessary. At the very least, could we not pass a function into `updateObjectFromXML`? The latter just calls the former immediately and uses the result to map properties onto. The complexity of a callback here seems to add no value -- couldn't the callback argument just be the object that function returns?

**Comment by ldko** [comment]
My initial thought was maybe it is in codalib because it is used by all of the coda Django apps, but it looks like `updateObjectFromXML` is only used in PES. Also, since the update (PUT) has been broken on PES (because of the eventIdentifier lookup failure I think), I don't think we have paid much attention to the function because it wasn't actually being called in practice. It makes sense to me to do the serialization in the models--or at least do something that is not use `updateObjectFromXML`.
