### ISSUE TITLE
bagatom.makeObjectFeed() errors if you pass a page number that doesn't exist

### ISSUE THREAD

**Issue by ldko** [unt-libraries/codalib#6]
EmptyPage exception is thrown on `object_list = paginator.page(page).object_list` (https://github.com/unt-libraries/codalib/blob/master/codalib/bagatom.py#L265) if a `page` value parameter is set to a page number that doesn't exist.

**Comment by runderwood** [comment]
This throws an EmptyPage exception, which I believe is now caught by all the code that calls this function.
